media_folder = "site/static/img"
public_folder = "img"

[backend]
name = "git-gateway"

[collections]
name = "post"
label = "Post"
folder = "site/content/post"
create = true

  [collections.fields]
  label = "Title"
  name = "title"
  widget = "string"

  [collections.fields]
  label = "Publish Date"
  name = "date"
  widget = "datetime"

  [collections.fields]
  label = "Intro Blurb"
  name = "description"
  widget = "text"

  [collections.fields]
  label = "Image"
  name = "image"
  widget = "image"
  required = false

  [collections.fields]
  label = "Body"
  name = "body"
  widget = "markdown"

[collections]
name = "pages"
label = "Pages"

  [collections.files]
  file = "site/content/_index.md"
  label = "Home Page"
  name = "home"

    [collections.files.fields]
    label = "Title"
    name = "title"
    widget = "string"

    [collections.files.fields]
    label = "Subtitle"
    name = "subtitle"
    widget = "string"

    [collections.files.fields]
    label = "Image"
    name = "image"
    widget = "image"

    [collections.files.fields]
    label = "Blurb"
    name = "blurb"
    widget = "object"

      [collections.files.fields.fields]
      label = "Heading"
      name = "heading"
      widget = "string"

      [collections.files.fields.fields]
      label = "Text"
      name = "text"
      widget = "text"

    [collections.files.fields]
    label = "Intro"
    name = "intro"
    widget = "object"

      [collections.files.fields.fields]
      label = "Heading"
      name = "heading"
      widget = "string"

      [collections.files.fields.fields]
      label = "Text"
      name = "text"
      widget = "text"

    [collections.files.fields]
    label = "Products"
    name = "products"
    widget = "list"

      [collections.files.fields.fields]
      label = "Image"
      name = "image"
      widget = "image"

      [collections.files.fields.fields]
      label = "Text"
      name = "text"
      widget = "text"

    [collections.files.fields]
    label = "Values"
    name = "values"
    widget = "object"

      [collections.files.fields.fields]
      label = "Heading"
      name = "heading"
      widget = "string"

      [collections.files.fields.fields]
      label = "Text"
      name = "text"
      widget = "text"

  [collections.files]
  file = "site/content/contact/_index.md"
  label = "Contact Page"
  name = "contact"

    [collections.files.fields]
    label = "Title"
    name = "title"
    widget = "string"

    [collections.files.fields]
    label = "Logo"
    name = "logo"
    widget = "image"

    [collections.files.fields]
    label = "Body"
    name = "body"
    widget = "markdown"

    [collections.files.fields]
    label = "Contact Entries"
    name = "contact_entries"
    widget = "list"

      [collections.files.fields.fields]
      label = "Heading"
      name = "heading"
      widget = "string"

      [collections.files.fields.fields]
      label = "Text"
      name = "text"
      widget = "text"

  [collections.files]
  file = "site/content/products/_index.md"
  label = "Products Page"
  name = "products"

    [collections.files.fields]
    label = "Title"
    name = "title"
    widget = "string"

    [collections.files.fields]
    label = "Image"
    name = "image"
    widget = "image"

    [collections.files.fields]
    label = "Heading"
    name = "heading"
    widget = "string"

    [collections.files.fields]
    label = "Description"
    name = "description"
    widget = "string"

    [collections.files.fields]
    label = "Intro"
    name = "intro"
    widget = "object"

      [collections.files.fields.fields]
      label = "Heading"
      name = "heading"
      widget = "string"

      [collections.files.fields.fields]
      label = "Description"
      name = "description"
      widget = "text"

      [collections.files.fields.fields]
      label = "Blurbs"
      name = "blurbs"
      widget = "list"

        [collections.files.fields.fields.fields]
        label = "Image"
        name = "image"
        widget = "image"

        [collections.files.fields.fields.fields]
        label = "Text"
        name = "text"
        widget = "text"

    [collections.files.fields]
    label = "Main"
    name = "main"
    widget = "object"

      [collections.files.fields.fields]
      label = "Heading"
      name = "heading"
      widget = "string"

      [collections.files.fields.fields]
      label = "Description"
      name = "description"
      widget = "text"

      [collections.files.fields.fields]
      label = "Image1"
      name = "image1"
      widget = "object"

        [collections.files.fields.fields.fields]
        label = "Image"
        name = "image"
        widget = "image"

        [collections.files.fields.fields.fields]
        label = "Alt"
        name = "alt"
        widget = "string"

      [collections.files.fields.fields]
      label = "Image2"
      name = "image2"
      widget = "object"

        [collections.files.fields.fields.fields]
        label = "Image"
        name = "image"
        widget = "image"

        [collections.files.fields.fields.fields]
        label = "Alt"
        name = "alt"
        widget = "string"

      [collections.files.fields.fields]
      label = "Image3"
      name = "image3"
      widget = "object"

        [collections.files.fields.fields.fields]
        label = "Image"
        name = "image"
        widget = "image"

        [collections.files.fields.fields.fields]
        label = "Alt"
        name = "alt"
        widget = "string"

    [collections.files.fields]
    label = "Testimonials"
    name = "testimonials"
    widget = "list"

      [collections.files.fields.fields]
      label = "Quote"
      name = "quote"
      widget = "string"

      [collections.files.fields.fields]
      label = "Author"
      name = "author"
      widget = "string"

    [collections.files.fields]
    label = "Full_image"
    name = "full_image"
    widget = "image"

    [collections.files.fields]
    label = "Pricing"
    name = "pricing"
    widget = "object"

      [collections.files.fields.fields]
      label = "Heading"
      name = "heading"
      widget = "string"

      [collections.files.fields.fields]
      label = "Description"
      name = "description"
      widget = "string"

      [collections.files.fields.fields]
      label = "Plans"
      name = "plans"
      widget = "list"

        [collections.files.fields.fields.fields]
        label = "Plan"
        name = "plan"
        widget = "string"

        [collections.files.fields.fields.fields]
        label = "Price"
        name = "price"
        widget = "string"

        [collections.files.fields.fields.fields]
        label = "Description"
        name = "description"
        widget = "string"

        [collections.files.fields.fields.fields]
        label = "Items"
        name = "items"
        widget = "list"

  [collections.files]
  file = "site/content/values/_index.md"
  label = "Values Page"
  name = "values"

    [collections.files.fields]
    label = "Title"
    name = "title"
    widget = "string"

    [collections.files.fields]
    label = "Image"
    name = "image"
    widget = "image"

    [collections.files.fields]
    label = "Values"
    name = "values"
    widget = "list"

      [collections.files.fields.fields]
      label = "Heading"
      name = "heading"
      widget = "string"

      [collections.files.fields.fields]
      label = "Text"
      name = "text"
      widget = "text"

      [collections.files.fields.fields]
      label = "Image"
      name = "imageUrl"
      widget = "image"